name: MTProxy Checker

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore Telethon session
        run: |
          echo "${{ secrets.SESSION_B64 }}" | base64 -d > session.session

      - name: Run script
        run: python main.py
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          RUPROXY_USER: ${{ secrets.RUPROXY_USER }}
          RUPROXY_PASS: ${{ secrets.RUPROXY_PASS }}

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add working_mtproxy.txt dead_mtproxy.txt README.md
          git commit -m "update proxies" || exit 0
          git push
